version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "17"
  language_version = "1.9"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "ktlint"